- name: Install dependencies
  action: apt pkg={{item}} state=installed
  with_items:
       - curl
       - facter
       - fail2ban
       - nginx
       - nginx-extras
       - uwsgi
       - git
       - python-pip
       - gcc
       - python-dev
       - libffi-dev

- name: configure nginx
  template:
    src: apiv1.nginx.j2
    dest: /etc/nginx/sites-enabled/apiv1    

- name: configure uwsgi
  template:
    src: apiv1.uwsgi.j2
    dest: /etc/uwsgi/apps-enabled/apiv1.ini

- name: copy caliopen packages
  copy:
    src: "{{ dist_directory }}/{{ caliopen_version }}/{{ item }}"
    dest: /var/tmp
  with_items:
    - caliopen_storage-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_main-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_api-{{ caliopen_version }}-py2.py3-none-any.whl

- name: install caliopen packages
  shell: cd /var/tmp && pip install {{ item }}
  with_items:
    - caliopen_storage-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_main-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_api-{{ caliopen_version }}-py2.py3-none-any.whl

- name: install caliopen API configuration file
  template:
    src: apiv1.ini.j2
    dest: /etc/caliopen/apiv1.ini

- name: install prometheus nginx metric exporter
  git:
    repo: "https://github.com/knyar/nginx-lua-prometheus.git"
    dest: /srv/nginx-lua-prometheus

- name: configure lua
  template: src=lua.conf.j2 dest=/etc/nginx/conf.d/lua.conf
  notify: restart nginx
