- name: Install dependencies
  action: apt pkg={{item}} state=installed
  with_items:
       - uwsgi
       - uwsgi-plugin-python
       - gcc
       - python-dev
       - libffi-dev

- name: create geoip2 databases directory
  file:
    path: /var/lib/geoip2
    state: directory
  tags:
    - geoip2

- name: install geoip2 databases
  unarchive:
    src: http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz
    dest: /var/lib/geoip2/
    remote_src: yes
  tags:
    - geoip2

- name: install geoip2 databases in top directory
  shell: mv /var/lib/geoip2/GeoLite2-Country_*/GeoLite2-Country.mmdb /var/lib/geoip2/GeoLite2-Country.mmdb
  tags:
    - geoip2

- name: configure uwsgi
  template:
    src: apiv1.uwsgi.j2
    dest: /etc/uwsgi/apps-enabled/apiv1.ini

- name: copy caliopen packages
  copy:
    src: "{{ dist_directory }}/{{ caliopen_version }}/{{ item }}"
    dest: /var/tmp
  with_items:
    - caliopen_storage-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_pi-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_main-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_api-{{ caliopen_version }}-py2.py3-none-any.whl
  tags:
    - deploy

- name: install caliopen packages
  shell: cd /var/tmp && pip install {{ item }}
  with_items:
    - caliopen_storage-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_pi-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_main-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_api-{{ caliopen_version }}-py2.py3-none-any.whl
  tags:
    - deploy

- name: install some missing python dependencies
  pip:
    name: "{{ item }}"
  with_items:
    - strict-rfc3339
    - webcolors

- name: install caliopen API configuration file
  template:
    src: apiv1.ini.j2
    dest: /etc/caliopen/apiv1.ini
  tags:
    - deploy

- name: install swagger.json
  copy:
    src: "{{ dist_directory }}/{{ caliopen_version }}/swagger.json"
    dest: /etc/caliopen/swagger.json
    mode: 0644
  tags:
    - deploy

- name: configure nginx
  template:
    src: apiv1.nginx.j2
    dest: /etc/nginx/sites-enabled/apiv1 
  notify: restart nginx

- name: configure filebeat
  template: 
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify: restart filebeat
