- name: install logstash
  apt:
    name: logstash
    state: present

- name: configure logstash 
  template: src=logstash.yml.j2 dest=/etc/logstash/conf.d/logstash.yml

- name: set logstash pipeline
  template: src=logstash.conf dest=/etc/logstash/conf.d/logstash.conf

- name: start logstash
  systemd:
    name: logstash
    state: started
