- name: create docker-registry directory
  file:
    path: "{{ registry_path }}"
    state: directory

- name: copy compose file for registry server
  copy: src=docker-compose.yml dest={{ registry_path }}/docker-compose.yml

- name: start docker-registry
  shell: docker-compose -f {{ registry_path }}/docker-compose.yml up -d

- name: create auth files directory
  file:
    path: /etc/nginx/auth
    state: directory

- name: copy registry pass file
  copy:
    src: registry.htpasswd
    dest: /etc/nginx/auth/registry.htpasswd

- name: configure nginx vhost
  template:
    src: docker-registry.nginx.j2
    dest: /etc/nginx/sites-enabled/docker-registry 

- name: restart service nginx
  service:
    name: nginx
    state: restarted
