- name: Update packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install dependencies
  action: apt pkg={{item}} state=installed
  with_items:
       - curl
       - facter
       - fail2ban
       - iptables

- name: enable ip forwarding
  shell: sysctl -w net.ipv4.ip_forward=1

- name: enable SNAT
  shell: iptables -t nat -A POSTROUTING -o eth0 -j SNAT --to {{ ansible_eth0.ipv4.address }}
