- name: configure nginx
  template:
    src: api.nginx.j2
    dest: /etc/nginx/sites-enabled/api
  notify: restart nginx

- name: configure filebeat
  template: 
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify: restart filebeat

