- name: add grafana apt source
  shell: echo "deb https://packagecloud.io/grafana/stable/debian/ jessie main"| tee /etc/apt/sources.list.d/packagecloud.list

- name: update packages
  apt:
      update_cache: yes
      upgrade: dist

- name: install packagecloud pgp key
  apt_key:
    id: C2E73424D59097AB
    url:  https://packagecloud.io/gpg.key
    state: present

- name: install grafana server
  apt:
    name: grafana
    state: present

- name: configure grafana server
  template: src=grafana.ini.j2 dest=/etc/grafana/grafana.ini

- name: start grafana service
  service: name=grafana-server state=started

- name: install nginx kibana prometheus pass
  copy: src={{ item }} dest=/etc/nginx/{{ item }}
  with_items:
    - ".htpasswd.pass"
    - ".htpasswd"

- name: configure nginx
  template:
    src: monitor.nginx.j2
    dest: /etc/nginx/sites-enabled/monitor    
  notify: restart nginx

- name: configure kibana
  template:
    src: monitor.kibana.j2
    dest: /etc/nginx/sites-enabled/kibana    
  notify: restart nginx

- name: configure prometheus
  template:
    src: monitor.prometheus.j2
    dest: /etc/nginx/sites-enabled/prometheus
  notify: restart nginx

- name: configure grafana
  template:
    src: monitor.grafana.j2
    dest: /etc/nginx/sites-enabled/grafana
  notify: restart nginx
