- name: Install dependencies
  action: apt pkg={{item}} state=installed
  with_items:
       - curl
       - facter
       - iptables
       - fail2ban

- name: add grafana apt source
  shell: echo "deb https://packagecloud.io/grafana/stable/debian/ jessie main"| tee /etc/apt/sources.list.d/packagecloud.list

- name: update packages
  apt:
      update_cache: yes
      upgrade: dist

- name: install packagecloud pgp key
  apt_key:
    id: C2E73424D59097AB
    url:  https://packagecloud.io/gpg.key
    state: present

- name: install grafana server
  apt:
    name: grafana
    state: present

- name: configure grafana server
  template: src=grafana.ini.j2 dest=/etc/grafana/grafana.ini

- name: start grafana service
  service: name=grafana-server state=started

- name: configure nginx
  template:
    src: monitor.nginx.j2
    dest: /etc/nginx/sites-enabled/monitor    
  notify: restart nginx