---
# defaults for postfix
postfix_install:
  - postfix
  - mailutils
postfix_hostname: "mail.{{ caliopen_domain_name }}"
postfix_mailname: "mail.{{ caliopen_domain_name }}"
postfix_aliases: []
postfix_virtual_aliases: []
postfix_sender_canonical_maps: []
postfix_generic: []
postfix_relayhost: false
postfix_relayhost_port: 587
postfix_relaytls: false
postfix_inet_interfaces: "{{ ansible_host }}"
postfix_inet_protocols: all
postfix_mydestination:
  - "{{ postfix_hostname }}"
  - localdomain
  - localhost
  - localhost.localdomain
postfix_mynetworks:
  - "{{ backend_ip }}"
postfix_smtpd_banner: '$myhostname ESMTP $mail_name'
postfix_disable_vrfy_command: false
postfix_message_size_limit: 20480000

# defaults for milters
milter_amavis_socket: "/var/run/amavis/amavisd.sock"
milter_amavis_milter_socket: "/var/run/amavis/amavisd-milter.sock"
milter_dkim_keys_dir: /etc/opendkim/keys
milter_dkim_key_file: key
milter_dkim_group: vmail
milter_spamass_db: spamassassin
milter_spamass_user: spamass
milter_spamass_user_override: vmail
