- name: install elasticsearch pgp key
  apt_key:
    id: D88E42B4
    keyserver: pgp.mit.edu
    state: present

- name: add es apt repositories
  shell: echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | tee /etc/apt/sources.list.d/elastic-5.x.list

- name: update packages
  apt:
      update_cache: yes
      upgrade: dist

- name: add apt-transport-https dependency
  apt:
    name: apt-transport-https
    state: present

- name: install elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: configure elasticsearch
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml

- name: configure elasticsearch jvm
  template: src=jvm.options dest=/etc/elasticsearch/jvm.options

- name: start elasticsearch
  systemd:
    name: elasticsearch
    state: started

- name: install kibana
  apt:
    name: kibana
    state: present

- name: configure kibana
  template: src=kibana.yml.j2 dest=/etc/kibana/kibana.yml

- name: start kibana
  systemd:
    name: kibana 
    state: started

