- name: install nats
  copy:
    src: "{{ dist_directory }}/ext/gnatsd-v{{ gnatsd_version }}-linux-amd64/gnatsd"
    dest: /usr/local/sbin/gnatsd
    mode: 0711

- name: install gnats service
  template: src=gnatsd.service.j2 dest=/etc/systemd/system/gnatsd.service

- name: start nats
  service: name=gnatsd state=started enabled=yes

- name: install prometheus-nats-exporter service
  template: src=prometheus-nats-exporter.service.j2 dest=/etc/systemd/system/prometheus-nats-exporter.service

- name: start prometheus-nats-exporter service
  service: name=prometheus-nats-exporter state=started enabled=yes
