- name: Install dependencies
  action: apt pkg={{item}} state=installed
  with_items:
       - curl
       - facter
       - iptables
       - fail2ban
       - unzip

- name: download nats server
  get_url:
    url: https://github.com/nats-io/gnatsd/releases/download/v1.0.2/gnatsd-v1.0.2-linux-amd64.zip
    dest: /var/tmp/gnatsd.zip

- name: unzip nats server
  unarchive:
    src: /var/tmp/gnatsd.zip
    dest: /var/tmp/
    remote_src: yes

- name: install nats
  copy:
    src: /var/tmp/gnatsd-v1.0.2-linux-amd64/gnatsd
    dest: /usr/local/sbin/gnatsd
    remote_src: yes
    mode: 0711

- name: install gnats service
  template: src=gnatsd.service.j2 dest=/etc/systemd/system/gnatsd.service

- name: start nats
  service: name=gnatsd state=started

- name: install prometheus-nats-exporter service
  template: src=prometheus-nats-exporter.service.j2 dest=/etc/systemd/system/prometheus-nats-exporter.service

- name: start prometheus-nats-exporter service
  service: name=prometheus-nats-exporter state=started
