- name: download alertmanager
  get_url:
    url: https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz
    dest: /var/tmp

- name: decompress alertmanager
  unarchive:
    src: /var/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes

- name: install service for alertmanager
  template: src=alertmanager.service.j2 dest=/etc/systemd/system/alertmanager.service


- name: create configuration directory
  file:
    path: /etc/prometheus
    state: directory

- name: configure alertmanager
  template: src=alertmanager.yml.j2 dest=/etc/prometheus/alertmanager.yml
  notify: restart alertmanager

