- name: Configure default ipv4 gateway
  shell: ip route add default via 192.168.1.254
  ignore_errors: yes

- name: Force apt to use only ipv4
  shell: echo 'Acquire::ForceIPv4 "true";' | tee /etc/apt/apt.conf.d/99force-ipv4

- name: Install dependencies
  action: apt pkg={{item}} state=installed
  with_items:
       - curl
       - facter
       - iptables
       - fail2ban
       - iptables-persistent

- name: copy iptables rules for v6
  template: src=ip6tables.j2 dest=/etc/iptables/rules.v6

- name: copy iptables rules for v4
  template: src=iptables.j2 dest=/etc/iptables/rules.v4

- name: start iptables-persistent
  shell: netfilter-persistent start
