- name: Configure default ipv4 gateway
  shell: ip route add default via 192.168.1.254
  ignore_errors: yes

- name: Force apt to use only ipv4
  shell: echo 'Acquire::ForceIPv4 "true";' | tee /etc/apt/apt.conf.d/99force-ipv4

- name: Install dependencies
  action: apt pkg={{item}} state=installed
  with_items:
       - curl
       - facter
       - iptables
       - fail2ban
