- name: Install dependencies
  action: apt pkg={{item}} state=installed
  with_items:
       - curl
       - facter
       - fail2ban
       - nginx

- name: download prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version}}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /var/tmp

- name: decompress prometheus
  unarchive:
    src: /var/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes

- name: install service for prometheus
  template: src=prometheus.service.j2 dest=/etc/systemd/system/prometheus.service

- name: install elasticsearch_exporter
  get_url:
    url: https://github.com/justwatchcom/elasticsearch_exporter/releases/download/v1.0.1/elasticsearch_exporter-1.0.1.linux-amd64.tar.gz
    dest: /var/tmp

- name: uncompress elasticsearch_exporter
  unarchive:
    src: /var/tmp/elasticsearch_exporter-1.0.1.linux-amd64.tar.gz
    dest: /var/tmp
    remote_src: yes
- name: copy elasticsearch_exporter to correct location
  shell: cp -p /var/tmp/elasticsearch_exporter-1.0.1.linux-amd64/elasticsearch_exporter /usr/local/bin

- name: install elasticsearch_exporter service
  template: src=elasticsearch_exporter.service.j2 dest=/etc/systemd/system/elasticsearch_exporter.service
  notify: start elasticsearch_exporter

- name: create configuration directory
  file:
    path: /etc/prometheus
    state: directory

- name: configure prometheus
  template: src=prometheus.yml.j2 dest=/etc/prometheus/prometheus.yml
  notify: restart prometheus

- name: configure nginx
  template: src=prometheus.nginx.j2 dest=/etc/nginx/sites-enabled/prometheus
  notify: restart nginx
