- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  with_items:
       - gcc
       - python-dev
       - libffi-dev
       - libssl-dev

- name: copy caliopen packages
  copy:
    src: "{{ dist_directory }}/{{ caliopen_version }}/{{ item }}"
    dest: /var/tmp
  with_items:
    - caliopen_storage-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_pi-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_main-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_pgp-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_nats-{{ caliopen_version }}-py2.py3-none-any.whl
  tags:
    - deploy

- name: install caliopen packages
  shell: cd /var/tmp && pip install {{ item }}
  with_items:
    - caliopen_storage-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_pi-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_main-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_pgp-{{ caliopen_version }}-py2.py3-none-any.whl
    - caliopen_nats-{{ caliopen_version }}-py2.py3-none-any.whl
  tags:
    - deploy

- name: install some missing python dependencies
  pip:
    name: "{{ item }}"
  with_items:
    - strict-rfc3339
    - webcolors

- name: install worker service
  template: src=caliopen-worker.service.j2 dest=/etc/systemd/system/caliopen-worker.service

- name: start worker service
  service: name=caliopen-worker state=started enabled=yes
 
- name: configure filebeat
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify: restart filebeat

- name: install caliopen remote identities poller and fetcher
  copy:
    src: "{{ dist_directory }}/{{ caliopen_version }}/{{ item }}"
    dest: /usr/local/bin
  with_items:
    - imapworker
    - idpoller

- name: copy caliopen imap worker configuration
  template:
    src: imapworker.yaml.j2
    dest: /etc/caliopen/imapworker.yaml

- name: copy caliopen identity poller configuration
  template:
    src: idpoller.yaml.j2
    dest: /etc/caliopen/idpoller.yaml