- name: create caliopen configuration directory
  file:
    path: /etc/caliopen
    state: directory

- name: install caliopen configuration file
  template:
    src: caliopen.yaml.template
    dest: /etc/caliopen/caliopen.yaml
  tags:
    - deploy

- name: download a decent pip version
  get_url:
    url: https://bootstrap.pypa.io/ez_setup.py
    dest: /var/tmp

- name: install pip
  shell: python /var/tmp/ez_setup.py

- name: upgrade pip
  shell: pip install --upgrade pip
