- name: install elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: configure elasticsearch
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml

- name: configure elasticsearch jvm
  template: src=jvm.options dest=/etc/elasticsearch/jvm.options

- name: start elasticsearch
  systemd:
    name: elasticsearch
    state: started
