- name: add node debian pgp key
  apt_key:
    id: 1655A0AB68576280
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add node debian repository
  shell: echo "deb https://deb.nodesource.com/node_6.x jessie main" > /etc/apt/sources.list.d/nodesource.list

- name: add yarn debian pgp key
  apt_key:
    id: 1646B01B86E50310
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: add yarn debian repository
  shell: echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

- name: update packages
  apt:
    update_cache: yes
    upgrade: dist

- name: install nodejs and yarn
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - yarn

- name: configure nginx
  template:
    src: caliopen_client.nginx.j2
    dest: /etc/nginx/sites-enabled/caliopen_client

- name: copy caliopen packages
  copy:
    src: "{{ dist_directory }}/{{ caliopen_version }}/client"
    dest: /opt/caliopen

- name: install node packages
  shell: yarn
  args:
    chdir: /opt/caliopen/client

- name: install client launcher
  template: src=start-client.j2 dest=/opt/caliopen/client/start-client mode=0755

- name: install web client service
  template: src=web-client.service.j2 dest=/etc/systemd/system/web-client.service

- name: start web client service
  service: name=web-client state=started

