- name: download minio
  get_url:
    url: https://dl.minio.io/server/minio/release/linux-amd64/minio
    dest: /usr/local/bin/minio
    mode: 0711

- name: create data directory
  file:
    path: /srv/data
    state: directory

- name: create minio configuration directory
  file:
    path: /etc/minio
    state: directory

- name: configure minio
  template: src=config.json.j2 dest=/etc/minio/config.json

- name: install minio service
  template: src=minio.service.j2 dest=/etc/systemd/system/minio.service

- name: enable minio service
  shell: systemctl enable minio.service

- name: start minio service
  shell: systemctl start minio.service
